#!/usr/bin/env node
// Stamps the build: docs/js/build.js (imported by the app) and docs/version.json
// (fetched with cache: 'no-store' at load) carry the same id. GitHub Pages sends
// max-age=600 on every file, so a tab opened before a deploy runs the old
// modules for up to ten minutes; the app compares the two ids and tells the
// user to hard-reload when they differ. Run before committing a web change.
import { writeFileSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { execSync } from 'node:child_process';
const id = new Date().toISOString().replace(/[-:]/g, '').slice(0, 15) + '-' + execSync('git rev-parse --short HEAD').toString().trim();
writeFileSync(new URL('../docs/js/build.js', import.meta.url), `// generated by scripts/stamp-build.mjs\nexport const BUILD = '${id}';\n`);
writeFileSync(new URL('../docs/version.json', import.meta.url), JSON.stringify({ build: id }) + '\n');
// service worker with the build's asset list (everything under docs/ the page can load)
const docs = new URL('../docs/', import.meta.url).pathname;
const assets = [];
(function walk(dir) { for (const name of readdirSync(dir)) { const p = join(dir, name); if (statSync(p).isDirectory()) walk(p); else { const rel = relative(docs, p); if (!/\.(md|html)$/.test(rel) || rel === 'index.html') if (rel !== 'sw.js' && rel !== 'test-web3.html') assets.push('./' + rel); } } })(docs);
const template = readFileSync(new URL('./sw.template.js', import.meta.url), 'utf8');
writeFileSync(join(docs, 'sw.js'), template.replace('__BUILD__', id).replace('__ASSETS__', JSON.stringify(assets.sort(), null, 2)));
console.log('build', id, 'sw assets', assets.length);
