#!/usr/bin/env node
// Stamps the build: docs/js/build.js (imported by the app) and docs/version.json
// (fetched with cache: 'no-store' at load) carry the same id. GitHub Pages sends
// max-age=600 on every file, so a tab opened before a deploy runs the old
// modules for up to ten minutes; the app compares the two ids and tells the
// user to hard-reload when they differ. Run before committing a web change.
import { writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
const id = new Date().toISOString().replace(/[-:]/g, '').slice(0, 15) + '-' + execSync('git rev-parse --short HEAD').toString().trim();
writeFileSync(new URL('../docs/js/build.js', import.meta.url), `// generated by scripts/stamp-build.mjs\nexport const BUILD = '${id}';\n`);
writeFileSync(new URL('../docs/version.json', import.meta.url), JSON.stringify({ build: id }) + '\n');
console.log('build', id);
